// Tests for the parts that touch the filesystem and the command line: how a
// package pattern turns into a directory, which files a walk picks up, the one
// rule that spans a whole package, and what -h and an unknown flag do to the
// output and the exit status. The per-file rules are in check_test.go.

package main

import (
	"errors"
	"flag"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestPatternRoot(t *testing.T) {
	cases := []struct {
		pattern   string
		root      string
		recursive bool
	}{
		{"./...", ".", true},
		{"...", ".", true},
		{"internal/cli", "internal/cli", false},
		{"internal/...", "internal", true},
		{".", ".", false},
	}
	for _, tc := range cases {
		root, recursive := patternRoot(tc.pattern)
		if root != tc.root || recursive != tc.recursive {
			t.Errorf("patternRoot(%q) = %q, %v; want %q, %v", tc.pattern, root, recursive, tc.root, tc.recursive)
		}
	}
}

func TestGoFilesSkipsWhatTheGoToolSkips(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "a.go"), "package p\n")
	write(t, filepath.Join(dir, "a_test.go"), "package p\n")
	write(t, filepath.Join(dir, "notes.md"), "hello\n")
	write(t, filepath.Join(dir, "sub", "b.go"), "package sub\n")
	write(t, filepath.Join(dir, "testdata", "bad.go"), "package testdata\n")
	write(t, filepath.Join(dir, ".hidden", "c.go"), "package hidden\n")
	write(t, filepath.Join(dir, "bin", "d.go"), "package bin\n")

	got, err := goFiles([]string{dir + "/..."})
	if err != nil {
		t.Fatalf("goFiles: %v", err)
	}
	want := []string{
		filepath.Join(dir, "a.go"),
		filepath.Join(dir, "a_test.go"),
		filepath.Join(dir, "sub", "b.go"),
	}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Errorf("goFiles =\n%v\nwant\n%v", got, want)
	}

	shallow, err := goFiles([]string{dir})
	if err != nil {
		t.Fatalf("goFiles: %v", err)
	}
	if len(shallow) != 2 {
		t.Errorf("non-recursive goFiles = %v, want the two files in the top directory", shallow)
	}
}

func TestSecondPackageCommentIsReported(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "doc.go"), "// Package p is the thing.\npackage p\n")
	write(t, filepath.Join(dir, "b.go"), "// Package p is the thing, again.\npackage p\n")

	findings, files, err := checkFiles([]string{filepath.Join(dir, "doc.go"), filepath.Join(dir, "b.go")})
	if err != nil {
		t.Fatalf("checkFiles: %v", err)
	}
	if files != 2 {
		t.Errorf("examined %d files, want 2", files)
	}
	if len(findings) != 1 || !strings.Contains(findings[0].Message, "second package comment") {
		t.Fatalf("findings = %v, want one about a second package comment", findings)
	}
}

func TestGeneratedFilesAreSkipped(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "gen.go"), "// Code generated by hand. DO NOT EDIT.\n\npackage p\n\nfunc F() {}\n")

	findings, files, err := checkFiles([]string{filepath.Join(dir, "gen.go")})
	if err != nil {
		t.Fatalf("checkFiles: %v", err)
	}
	if files != 0 || len(findings) != 0 {
		t.Errorf("examined %d files with %v, want a generated file to be skipped", files, findings)
	}
}

func TestRunReportsFindingsAndCounts(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "a.go"), "package p\n\nfunc F() {}\n")

	var out, problems strings.Builder
	n, err := run([]string{dir + "/..."}, &out, &problems)
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if n != 2 {
		t.Errorf("run found %d, want 2 (missing header, undocumented F)", n)
	}
	if !strings.Contains(problems.String(), "no header comment") ||
		!strings.Contains(problems.String(), "func F has no doc comment") {
		t.Errorf("problems =\n%s", problems.String())
	}
	if !strings.Contains(out.String(), "undocumented item(s)") {
		t.Errorf("summary = %q", out.String())
	}
}

func TestRunOnACleanPackageSaysSo(t *testing.T) {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "doc.go"), "// Package p is the thing.\npackage p\n")
	write(t, filepath.Join(dir, "a.go"), "// Owns F.\n\npackage p\n\n// F does a thing.\nfunc F() {}\n")

	var out strings.Builder
	n, err := run([]string{dir + "/..."}, &out, io.Discard)
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if n != 0 {
		t.Errorf("run found %d findings on a clean package", n)
	}
	if !strings.Contains(out.String(), "2 file(s) documented") {
		t.Errorf("summary = %q", out.String())
	}
}

func TestRunRejectsAMissingDirectory(t *testing.T) {
	if _, err := run([]string{filepath.Join(t.TempDir(), "nope")}, io.Discard, io.Discard); err == nil {
		t.Error("run on a missing directory returned no error")
	}
}

func TestRunHelpPrintsUsageToStdout(t *testing.T) {
	for _, flagName := range []string{"-h", "-help", "--help"} {
		t.Run(flagName, func(t *testing.T) {
			var out, problems strings.Builder
			n, err := run([]string{flagName}, &out, &problems)
			if !errors.Is(err, flag.ErrHelp) {
				t.Fatalf("run(%s) error = %v, want flag.ErrHelp", flagName, err)
			}
			if n != 0 {
				t.Errorf("run(%s) counted %d findings, want 0", flagName, n)
			}
			for _, want := range []string{"usage: doccheck [packages...]", "header comment", "Exit status:", "\n  2  "} {
				if !strings.Contains(out.String(), want) {
					t.Errorf("usage on stdout lacks %q:\n%s", want, out.String())
				}
			}
			if problems.Len() != 0 {
				t.Errorf("help wrote to stderr: %q", problems.String())
			}
			if code := exitStatus(n, err); code != 0 {
				t.Errorf("exit status for help = %d, want 0", code)
			}
		})
	}
}

func TestRunRejectsAnUnknownFlag(t *testing.T) {
	var out, problems strings.Builder
	n, err := run([]string{"-x", "./..."}, &out, &problems)
	var usageErr usageError
	if !errors.As(err, &usageErr) {
		t.Fatalf("run(-x) error = %v, want a usageError", err)
	}
	if !strings.Contains(err.Error(), "-x") || !strings.Contains(err.Error(), "doccheck -h") {
		t.Errorf("error = %q, want it to name the flag and point at -h", err)
	}
	if n != 0 || out.Len() != 0 || problems.Len() != 0 {
		t.Errorf("an unknown flag ran the checker: n=%d out=%q problems=%q", n, out.String(), problems.String())
	}
	if code := exitStatus(n, err); code != exitUsage {
		t.Errorf("exit status for an unknown flag = %d, want %d", code, exitUsage)
	}
}

func TestExitStatus(t *testing.T) {
	cases := []struct {
		name string
		n    int
		err  error
		want int
	}{
		{"clean", 0, nil, 0},
		{"findings", 3, nil, exitFailure},
		{"walk error", 0, errors.New("walking nope: no such file"), exitFailure},
		{"help", 0, flag.ErrHelp, 0},
		{"usage", 0, usageError{err: errors.New("flag provided but not defined: -x")}, exitUsage},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := exitStatus(tc.n, tc.err); got != tc.want {
				t.Errorf("exitStatus(%d, %v) = %d, want %d", tc.n, tc.err, got, tc.want)
			}
		})
	}
}

func TestParseArgsPatterns(t *testing.T) {
	patterns, err := parseArgs(nil, io.Discard)
	if err != nil {
		t.Fatalf("parseArgs(nil): %v", err)
	}
	if len(patterns) != 1 || patterns[0] != "./..." {
		t.Errorf("parseArgs(nil) = %v, want [./...]", patterns)
	}
	patterns, err = parseArgs([]string{"--", "-h"}, io.Discard)
	if err != nil {
		t.Fatalf("parseArgs(--, -h): %v", err)
	}
	if len(patterns) != 1 || patterns[0] != "-h" {
		t.Errorf("parseArgs(--, -h) = %v, want the -h after -- kept as a pattern", patterns)
	}
}

// write creates a file and the directories above it, failing the test rather
// than returning an error: a fixture that cannot be written is not a test
// result.
func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}
